# Generated by Django 3.1.1 on 2020-10-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qoutes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stocks',
            new_name='stock',
        ),
    ]
